### PR TITLE
Make package purpose slightly clearer

### PR DESCRIPTION
**Pull request by jimgar**
Hi @mdneuzerling 

This PR comes from [this issue comment](https://github.com/mdneuzerling/lambdr/issues/33#issuecomment-2228592673). Specifically I have attempted to address

> The basics of how Lambda works and why we need lambdr for R projects (contextualises the need for the package)

About which I said

> I think this one could just be a couple or few sentences added to the existing readme/site homepage. And probably just the 'why', not the 'how'.

I kept this PR quite tightly scoped for now, so haven't changed the existing example further down on the README. I should have the new Rocker image example ready in up to another 2, maybe 3 weeks. If you wanted to keep the PR open I'm happy to switch the example over at that point and push it up. Otherwise equally happy if you want to merge this one in (if it passes review!) and then I can make a subsequent 'example update' PR that updates both the README and vignette.

### CODE REVIEW

**Review by mdneuzerling — APPROVED** [review]
Fantastic! Thank you so much for helping with this.

**Comment by mdneuzerling** [comment]
The package checks are failing at the pkgdown building step. I'll take a look at those this week. But I don't see that as a reason to prevent merging this.

**Comment by mdneuzerling** [comment]
A heads up @jimgar that the pkgdown workflow has been fixed and [the updated website is online](https://lambdr.mdneuzerling.com/).

**Comment by jimgar** [comment]
Thank you @mdneuzerling! 

I have finished the Docker vignette and have started on re-working the placing-in-a-container one as well. Life's just been busy. But I'll get a PR up for those soon for your feedback and consideration :)

**Pull request merged**
